<a href="https://colab.research.google.com/github/kesavan1994/Sentiment-Analyzer/blob/master/Sentiment_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MDB dataset having 50K movie reviews for natural language processing or Text analytics.
This is a dataset for binary sentiment classification containing substantially more data than previous benchmark datasets. We provide a set of 25,000 highly polar movie reviews for training and 25,000 for testing. So, predict the number of positive and negative reviews using either classification or deep learning algorithms.
For more dataset information, please go through the following link,
http://ai.stanford.edu/~amaas/data/sentiment/

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import pandas as pd

data=pd.read_csv('/content/drive/MyDrive/Data_set/IMDB Dataset.csv')
df=pd.DataFrame(data)

In [ ]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df.columns

Index(['review', 'sentiment'], dtype='object')

In [ ]:
df.shape

(50000, 2)

In [ ]:
df.describe()

review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [ ]:
df.isna().sum()

review       0
sentiment    0
dtype: int64

In [ ]:
df['sentiment'].value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

Text Normalization

Tokenization

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
from nltk.tokenize import ToktokTokenizer
from nltk.corpus import stopwords

tokenizers=ToktokTokenizer()
stopwords=stopwords.words('english')

In [ ]:
from bs4 import BeautifulSoup
import re
def noiseremoval(text):
    soup=BeautifulSoup(text,'html.parser')
    text=soup.get_text()
    text=re.sub("\[[^]]*\]",'',text)
    text=re.sub("[^A-Za-z]"," ",text)
    text=text.lower()
    return(text)

In [ ]:
# text="""The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
#   soup=BeautifulSoup(text,'html.parser')"""

# text=re.sub("[^A-Za-z]",' ',text)
# print(text)

In [ ]:
df['review']=df['review'].apply(noiseremoval)

<ipython-input-11-d44d6a048644>:4: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup=BeautifulSoup(text,'html.parser')


In [ ]:
df.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production  the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there s a family where a little boy ...  negative
4  petter mattei s  love in the time of money  is...  positive

Steamming

In [ ]:
from nltk.stem import PorterStemmer

Lemmentition

In [ ]:
from nltk.stem import WordNetLemmatizer
def lem(text):
  lemme=WordNetLemmatizer()
  text=' '.join([lemme.lemmatize(word) for word in text.split()])
  return text

In [ ]:
df['review']=df['review'].apply(lem)

In [ ]:
df.head()

review sentiment
0  one of the other reviewer ha mentioned that af...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this wa a wonderful way to spend tim...  positive
3  basically there s a family where a little boy ...  negative
4  petter mattei s love in the time of money is a...  positive

In [ ]:
from nltk.tokenize import sent_tokenize
def removing_stopwords(text,is_lower_case=False):
  
  tokens=sent_tokenize(text)
  tokens=[i.strip() for i in tokens]
  if is_lower_case:
    filtokens=[i for i in tokens if i.lower() not in stopwords]
  else:
    filtokens=[i for i in tokens if i.lower() not in stopwords]  
  filtered_texts=' '.join(filtokens)
  return filtered_texts

In [ ]:
df['review']=df['review'].apply(removing_stopwords)

In [ ]:
df['review']

0        one of the other reviewer ha mentioned that af...
1        a wonderful little production the filming tech...
2        i thought this wa a wonderful way to spend tim...
3        basically there s a family where a little boy ...
4        petter mattei s love in the time of money is a...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    i m going to have to disagree with the previou...
49999    no one expects the star trek movie to be high ...
Name: review, Length: 50000, dtype: object

Normalization

In [ ]:
from sklearn.preprocessing import LabelBinarizer
# labeling the sentimet data

label=LabelBinarizer()
#transformed sentiment data

sentiment_data=label.fit_transform(df['sentiment'])
print(sentiment_data)


[[1]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]


Train & Test split

In [ ]:
X=df['review']    
y=df['sentiment']

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=221)

print("x_Train:",x_train.shape)
print("x_Test:",x_test.shape)
print("y_Train:",y_train.shape)
print("y_Test:",y_test.shape)

x_Train: (40000,)
x_Test: (10000,)
y_Train: (40000,)
y_Test: (10000,)


In [ ]:
train_review=df['review'][:30000]
test_review=df['review'][30000:]

Bag of words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
 # countVectorizer bag of words
cv=CountVectorizer()
 # Tranformed train reviews
cv_train=cv.fit_transform(train_review)
# transformed test reviews
cv_test=cv.transform(test_review)

print("BOW_CV_train:",cv_train.shape)
print("BOW_CV_test:",cv_test.shape)

BOW_CV_train: (30000, 73604)
BOW_CV_test: (20000, 73604)


In [ ]:
tf=TfidfVectorizer()
#  # Tranformed train reviews
tf_train=tf.fit_transform(train_review)
# # transformed test reviews
tf_test=tf.transform(test_review)

print("BOW_CV_train:",tf_train.shape)
print("BOW_CV_test:",tf_test.shape)

BOW_CV_train: (30000, 73604)
BOW_CV_test: (20000, 73604)


Label encoding

In [ ]:
train_df=df['sentiment'][:30000]
test_df=df['sentiment'][30000:]

Model creation:

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,classification_report

tvec = TfidfVectorizer()
log = LogisticRegression(solver = "lbfgs")

In [ ]:
from sklearn.pipeline import Pipeline
model = Pipeline([('vectorizer',tvec),('classifier',log)])

model.fit(x_train, y_train)
y_pred= model.predict(x_test)

print(confusion_matrix(y_pred, y_test))
print("Accuracy : ", accuracy_score(y_pred, y_test))
print("classification : ", classification_report(y_pred, y_test))
print('AOC',roc_auc_score(y_test,model.predict_proba(x_test)[:,1]))

[[4320  460]
 [ 607 4613]]
Accuracy :  0.8933
classification :                precision    recall  f1-score   support

    negative       0.88      0.90      0.89      4780
    positive       0.91      0.88      0.90      5220

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000

AOC 0.961621939332588


Save Model in pickle

In [ ]:
import pickle 

with open('model.pkl','wb') as files:
  pickle.dump(model,files)

In [ ]:
with open('/content/model.pkl' , 'rb') as f:
    sent = pickle.load(f)

In [ ]:
example = ["""Vijay Rajendran is a unhappy to-go lucky man. 
               Things change when his father becomes terminally ill, and he is left to manage his business empire."""]
result = sent.predict(example)
print(result)

['negative']


In [ ]:
example = ["I thought the cast was great. Brianna and Emma were exceptionaly talented in thier characters. Fun film.."]
result = model.predict(example)

print(result)

['positive']


In [ ]:
if result =='positive':
  print( 'yes')

yes


this another model createion

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,classification_report
log=LogisticRegression(penalty='l2',max_iter=500,C=1,random_state=42)
log.fit(cv_train,train_df)
y_pred=log.predict(cv_test)

print('Accurancy:',accuracy_score(test_df,y_pred))
print('Confusion_Matrix: ',confusion_matrix(test_df,y_pred))
log_auc=roc_auc_score(test_df,log.predict_proba(cv_test)[:,1])
print(log_auc)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accurancy: 0.88115
Confusion_Matrix:  [[8770 1245]
 [1132 8853]]
0.9479723129377041


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,roc_auc_score,classification_report
log_tf=LogisticRegression(penalty='l2',max_iter=500,C=1,random_state=42)
log_tf.fit(tf_train,train_df)
y_pred=log_tf.predict(tf_test)

print('Accurancy:',accuracy_score(test_df,y_pred))
print('Confusion_Matrix: ',confusion_matrix(test_df,y_pred))
log_auc=roc_auc_score(test_df,log.predict_proba(tf_test)[:,1])
print(log_auc)

Accurancy: 0.8907
Confusion_Matrix:  [[8821 1194]
 [ 992 8993]]
0.9412115877260724


In [ ]:
from sklearn import svm
clf=svm.SVC(kernel='rbf',)
clf.fit(cv_train,train_df)
y_pred=clf.predict(cv_test)
print('Accurancy:',accuracy_score(test_df,y_pred))
print('Confusion_Matrix: ',confusion_matrix(test_df,y_pred))
svm_auc=roc_auc_score(test_df,clf.predict_proba(cv_test)[:,1])
print(log_auc)

In [ ]:
print(y_pred)
print()



[['positive']
 ['negative']
 ['negative']
 ...
 ['positive']
 ['negative']
 ['negative']]



In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

tvec = TfidfVectorizer()
log = LogisticRegression(solver = "lbfgs")

In [ ]:
from sklearn.pipeline import Pipeline
model = Pipeline([('vectorizer',tvec),('classifier',log)])

model.fit(x_train, y_train)
y_pred= model.predict(x_test)

print(confusion_matrix(y_pred, y_test))
print("Accuracy : ", accuracy_score(y_pred, y_test))
print("classification : ", classification_report(y_pred, y_test))
print('AOC',roc_auc_score(y_test,model.predict_proba(x_test)[:,1]))

[[4317  459]
 [ 610 4614]]
Accuracy :  0.8931
classification :                precision    recall  f1-score   support

    negative       0.88      0.90      0.89      4776
    positive       0.91      0.88      0.90      5224

    accuracy                           0.89     10000
   macro avg       0.89      0.89      0.89     10000
weighted avg       0.89      0.89      0.89     10000

AOC 0.9616199789147055


In [ ]:
example = ["I thought the cast was great. Brianna and Emma were exceptionaly talented in thier characters. Fun film.."]
result = model.predict(example)

print(result)

['negative']
